/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:31d0be66-9edf-47b7-ae2a-702b4e69643d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_VwIWJyaGG",
    "aws_user_pools_web_client_id": "7ik2ju7qqv4tv8qiu71i1vqtgh",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://nyb7jyk3qvggll2kmepcyp3jce.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-jtygm46ukfcnbb5x53f4edqb54"
};


export default awsmobile;
